# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run unit tests
      run: |
        cd test_files
        cd unit_tests
        python unit_test.py

    - name: Run Job Application integration tests
      run: |
        cd test_files
        cd integration_tests
        python job_application_intergation_test.py

    - name: Run Login Details integration tests
      run: |
        cd test_files
        cd integration_tests
        python login_details_integration_test.py

    - name: Run Role Applicant Filter integration tests
      run: |
        cd test_files
        cd integration_tests
        python role_applicant_filter_integration_test.py

    - name: Run Role Applicant integration tests
      run: |
        cd test_files
        cd integration_tests
        python role_applicants_integration_test.py

    - name: Run Role Creation integration tests
      run: |
        cd test_files
        cd integration_tests
        python role_creation_integration_test.py

    - name: Run Role Listing Filter integration tests
      run: |
        cd test_files
        cd integration_tests
        python role_listing_filter_integration_test.py

    - name: Run Role Listing integration tests
      run: |
        cd test_files
        cd integration_tests
        python role_listings_integration_test.py

    - name: Run Staff Profile integration tests
      run: |
        cd test_files
        cd integration_tests
        python staff_profile_integration_test.py

    - name: Setup MySQL Database
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306
        container port: 3306
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql version: '8.0'
        mysql database: 'sbrp'
        mysql root password: ''
        mysql user: 'root'
        mysql password: 'root'

    - name: Install MySQL Client
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client

    - name: Run MySQL Client
      run: |
        sudo /etc/init.d/mysql start
        cat database/test_database.sql | sudo mysql -u root --password=root

    - name: Check if DB is running
      run: |
        sudo service mysql status

    - name: Start Flask Application
      run: |
        cd backend
        python app.py &

    # - name: Run Selenium Test Cases (Staff)
    #   run:
    #     cd test_files
    #     python selenium_test.py

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Install Vue CLI
      run: npm install -g @vue/cli

    - name: Build Vue.js application
      run: npm run build

    - name: Run Vue.js application
      run: npm run serve &

    - name: Wait for Vue.js application to start
      run: sleep 120  

    - name: Run Selenium Test Cases (Staff)
      run: |
        pwd
        ls -l test_files/end_to_end
        cd test_files/end_to_end && python staff_selenium_test.py
      shell: /usr/bin/bash -e {0}
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.10.13/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib

    - name: Run Selenium Test Cases (HR)
      run: |
        pwd
        ls -l test_files/end_to_end
        cd test_files/end_to_end && python hr_selenium_test.py
      shell: /usr/bin/bash -e {0}
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.10.13/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib




      # - name: Run Selenium Test Cases (HR)
      #   run:
      #     cd test_files
      #     cd selenium_tests
      #     python hr_selenium_test.py