# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [unit, integration]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Cache your dependencies to speed up the build process
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Installing dependencies needed
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Linting with flake8
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Parallel Test Execution For Unit and Integration Tests
    - name: Run tests
      run: |
        if [ "${{ matrix.test-type }}" == "unit" ]; then
          cd test_files/unit_tests
        elif [ "${{ matrix.test-type }}" == "integration" ]; then
          cd test_files/integration_tests
        fi
        python -m pytest


jobs:
  setup-and-run-selenium-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    
    # Setting up SQL database
    - name: Setup MySQL Database
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306
        container port: 3306
        character set server: 'utf8'
        collation server: 'utf8_general_ci'
        mysql version: '8.0'
        mysql database: 'sbrp'
        mysql root password: ''
        mysql user: 'root'
        mysql password: 'root'

    # Installing MySQL Client
    - name: Install MySQL Client
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client

    # Running MySQL Client
    - name: Run MySQL Client
      run: |
        sudo /etc/init.d/mysql start
        cat database/test_database.sql | sudo mysql -u root --password=root

    # Check if DB is running
    - name: Check if DB is running
      run: |
        sudo service mysql status

    # Starting Flask Application (backend)
    - name: Start Flask Application
      run: |
        cd backend
        python app.py &

    # Setting up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14

    # Cache your dependencies to speed up the build process
    - name: Cache Node.js
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Installing dependencies for Vue.js
    - name: Install dependencies
      run: npm install

    # Installing Vue CLI
    - name: Install Vue CLI
      run: npm install -g @vue/cli

    # Building Vue.js application
    - name: Build Vue.js application
      run: npm run build

    # Running Vue.js application
    - name: Run Vue.js application
      run: npm run serve &

    # Waiting for Vue.js application to start
    - name: Wait for Vue.js application to start
      run: sleep 60  

    # Running Selenium Test Cases
    - name: Run Selenium Test Cases
      run: |
        pwd
        ls -l test_files/end_to_end
        cd test_files/end_to_end && python selenium_test.py
      shell: /usr/bin/bash -e {0}
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.10.13/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.13/x64/lib

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test_files/test_results.xml
